trigger:
  - master
pool:
  vmImage: ubuntu-latest
stages:
  - stage: BuildKG
    displayName: Build Stage
    jobs:
      - job: BuildJob
        displayName: Build Job
        steps:
          - |-
            - script: >-
                                response=$(curl -s -o /dev/null -w "%{http_code}"
                                https://61fba1a087801d0017a2c626.mockapi.io/api/v1/checkResponse); if [ "$response" -ne 200 ]; then exit 1;
                                fi
                              displayName: Check API Response
          - script: 'echo "Organization URL: $(System.TeamFoundationCollectionUri)"'
            displayName: Print Organization URL
          - script: 'echo "Project Name: $(System.TeamProject)"'
            displayName: Print Project Name
          - checkout: self
          - script: >
              echo "Repo URL:
              https://github.com/kgoswami-cc/aws-ses-serverless-example" 

              #exit 1
  - stage: TestKG
    displayName: Test Stage
    dependsOn: BuildKG
    jobs:
      - job: TestJob
        displayName: Test Job
        steps:
          - script: 'echo "Organization URL: $(System.TeamFoundationCollectionUri)"'
            displayName: Print Organization URL
          - script: 'echo "Project Name: $(System.TeamProject)"'
            displayName: Print Project Name
          - checkout: self
          - script: >-
              echo "Repo URL:
              https://github.com/kgoswami-cc/aws-ses-serverless-example"
            displayName: Print Repo URL
          - script: npm install
            displayName: Install Dependencies
          - script: npm test
            displayName: Run Tests
