name: Node.js CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
          - 18.x
    steps:
      - name: ASPM Gate Check
        run: |-
          |
                                      response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3001/gatecheck?source=github&pipelineId=107278701&tenantId=02e24def-3903-4979-85b7-757a612cc3af); if [ "$response" -ne 200 ]; then exit 1; fi
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
